name: pre-commit check

on:
  workflow_call:

jobs:
  pre-commit-push:
    name: pre-commit check on Push
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - uses: pre-commit/action@v3.0.1

  pre-commit-pr:
    name: pre-commit check on PR
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}

    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

        # pull_request_target checkout the base of the repo
        # We need to checkout the actual pr to lint the changes.
      - name: Checkout pr
        run: gh pr checkout ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - id: run-pre-commit
        uses: pre-commit/action@v3.0.1

        # reviewdog posts suggested changes from pre-commit on the PR when hooks fail.
      - name: suggester / pre-commit
        uses: reviewdog/action-suggester@v1
        if: ${{ failure() && steps.run-pre-commit.conclusion == 'failure' }}
        with:
          tool_name: pre-commit
          level: warning
          reviewdog_flags: "-fail-level=error"
